"""Add detailed character personality fields

Revision ID: 086914fa157b
Revises: 47b3823eff09
Create Date: 2024-09-08 16:18:32.133215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '086914fa157b'
down_revision: Union[str, None] = '47b3823eff09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('scenario', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('category', sa.String(length=100), nullable=True)) # Assuming max_length based on name
    op.add_column('character', sa.Column('language', sa.String(length=10), nullable=True)) # Assuming short language codes
    op.add_column('character', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('voice_id', sa.String(), nullable=True))
    op.add_column('character', sa.Column('personality_traits', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('writing_style', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('background', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('knowledge_scope', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('quirks', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('emotional_range', sa.Text(), nullable=True))
    op.add_column('character', sa.Column('popularity_score', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('character', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('character', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('character', sa.Column('admin_feedback', sa.Text(), nullable=True))
    op.create_index(op.f('ix_character_category'), 'character', ['category'], unique=False)
    # Note: creator_id index should already exist from initial migration if FK was set up
    op.create_index(op.f('ix_character_language'), 'character', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_language'), table_name='character')
    op.drop_index(op.f('ix_character_category'), table_name='character')
    op.drop_column('character', 'admin_feedback')
    op.drop_column('character', 'is_featured')
    op.drop_column('character', 'is_public')
    op.drop_column('character', 'popularity_score')
    op.drop_column('character', 'emotional_range')
    op.drop_column('character', 'quirks')
    op.drop_column('character', 'knowledge_scope')
    op.drop_column('character', 'background')
    op.drop_column('character', 'writing_style')
    op.drop_column('character', 'personality_traits')
    op.drop_column('character', 'voice_id')
    op.drop_column('character', 'tags')
    op.drop_column('character', 'language')
    op.drop_column('character', 'category')
    op.drop_column('character', 'scenario')
    # ### end Alembic commands ### 