"""create_ai_provider_config_table

Revision ID: 6c48a894a48d
Revises: 4c8b46c6f4ab
Create Date: 2025-05-29 22:00:53.308406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision = '6c48a894a48d'
down_revision = '4c8b46c6f4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_config',
    sa.Column('active_provider_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_ai_provider_config_active_provider_name'), 'ai_provider_config', ['active_provider_name'], unique=False)
    # ### end Alembic commands ###

    # Insert initial data
    ai_provider_config_table = table(
        'ai_provider_config',
        column('id', Integer),
        column('active_provider_name', String)
    )
    op.bulk_insert(ai_provider_config_table,
        [
            {'id': 1, 'active_provider_name': 'gemini'}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_provider_config_active_provider_name'), table_name='ai_provider_config')
    op.drop_table('ai_provider_config')
    # ### end Alembic commands ###
